# Assignment 4 of ML <br> 21-27-10 Data Science

Nishchal Karwade

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv("iris.csv.csv")

In [5]:
df

sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

# Data Preprocessing & Splitting the data

In [6]:
X = df.iloc[ :, :-1]
y = df.iloc[ :,  -1]

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state= 1)

# Normalizing
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test  = sc.fit_transform(X_test)

# Encoding to 001,002,003 
from sklearn.preprocessing import LabelEncoder
lb = LabelEncoder()
y_train = lb.fit_transform(y_train)
y_test = lb.fit_transform(y_test)

# KNN Model - default

In [7]:
# KNeighborsClassifier
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier() # n = 5 default
# metric = 'minkowesi' - default

# Fitting of data
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)

# Metric

In [8]:
from sklearn.metrics import confusion_matrix, accuracy_score
CR = confusion_matrix(y_test, y_pred)
print(CR)
accuracy_score(y_test, y_pred)

# Diagonal are correct prediction of different classes
# elments to the side of 11 - sum of them is error

[[11  0  0]
 [ 0  8  5]
 [ 0  0  6]]


0.8333333333333334

# KNN - Neighbours n = 1

In [9]:
knn1 = KNeighborsClassifier(n_neighbors = 1) # n = 1 
# metric = 'minkowesi' - default

# Fitting of data
knn1.fit(X_train, y_train)
y_pred = knn1.predict(X_test)

from sklearn.metrics import confusion_matrix, accuracy_score
CR = confusion_matrix(y_test, y_pred)
print(CR)
accuracy_score(y_test, y_pred)

[[11  0  0]
 [ 0  7  6]
 [ 0  0  6]]


0.8

# KNN - Neighbours n = 2

In [10]:
knn2 = KNeighborsClassifier(n_neighbors = 2)

# Fitting of data
knn2.fit(X_train, y_train)
y_pred = knn2.predict(X_test)

from sklearn.metrics import confusion_matrix, accuracy_score
CR = confusion_matrix(y_test, y_pred)
print(CR)
accuracy_score(y_test, y_pred)

[[11  0  0]
 [ 0 11  2]
 [ 0  0  6]]


0.9333333333333333

# KNN - Neighbours n = 3

In [11]:
knn3 = KNeighborsClassifier(n_neighbors = 3)

# Fitting of data
knn3.fit(X_train, y_train)
y_pred = knn3.predict(X_test)

from sklearn.metrics import confusion_matrix, accuracy_score
CR = confusion_matrix(y_test, y_pred)
print(CR)
accuracy_score(y_test, y_pred)

[[11  0  0]
 [ 0  8  5]
 [ 0  0  6]]


0.8333333333333334

# KNN Model - eucliedean metric

In [12]:
euc = KNeighborsClassifier(n_neighbors = 2, metric = 'euclidean')
euc.fit(X_train, y_train)
pred_euc = euc.predict(X_test)
pred_euc

array([0, 1, 1, 0, 2, 2, 2, 0, 0, 2, 1, 0, 2, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       2, 0, 2, 1, 0, 0, 1, 2])

# Metric

In [13]:
CR_euc = confusion_matrix(y_test, pred_euc)
print(CR_euc)
accuracy_score(y_test, pred_euc)

# Diagonal are correct prediction of different classes
# elments to the side of 11 - sum of them is error

[[11  0  0]
 [ 0 11  2]
 [ 0  0  6]]


0.9333333333333333